package com.gtnh.processingplus.materials;

import gregtech.api.enums.Dyes;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.TierEU;
import gregtech.api.interfaces.IMaterialHandler;

public class GTNHPPMaterials implements IMaterialHandler {

    public static Materials Nylon66;
    public static Materials PolylacticAcid;
    public static Materials Kapton;
    public static Materials SinteredSiliconCarbide;
    public static Materials PAASolution;
    public static Materials TEOS;
    public static Materials HexagonalBoronNitride;
    public static Materials CarbonFiberComposite;
    public static Materials SilicaAerogel;

    // NEW FLUIDS
    public static Materials AdipicAcid;
    public static Materials Hexamethylenediamine;
    public static Materials Cyclohexanol;
    public static Materials KetoneAlcholSolution;
    public static Materials Cyclohexene;

    @Override
    public void onMaterialsInit() {

        /*
         * =========================
         * POLYMERS / SOLIDS
         * =========================
         */

        Nylon66 = new MaterialBuilder()
            .setName("Nylon66")
            .setDefaultLocalName("Nylon-6,6")
            .setChemicalFormula("(C₁₂H₂₂N₂O₂)")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF5EAD0)
            .setMoltenARGB(0xFFD4C8A0)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .addFluid()
            .setMeltingPoint(533)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        Nylon66.mMetaItemSubID = 953;
        Nylon66.setProcessingMaterialTierEU(TierEU.RECIPE_ZPM);

        PolylacticAcid = new MaterialBuilder()
            .setName("PolylacticAcid")
            .setDefaultLocalName("Polylactic Acid")
            .setChemicalFormula("(C₃H₄O₂)")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF5F5F0)
            .setMoltenARGB(0xFFD8D8D0)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .addFluid()
            .setMeltingPoint(453)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        PolylacticAcid.mMetaItemSubID = 954;
        PolylacticAcid.setProcessingMaterialTierEU(TierEU.RECIPE_ZPM);

        Kapton = new MaterialBuilder()
            .setName("Kapton")
            .setDefaultLocalName("Polyimide (Kapton)")
            .setChemicalFormula("(C₂₂H₁₀N₂O₅)")
            .setColor(Dyes.dyeYellow)
            .setARGB(0xFFCC8800)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        Kapton.mMetaItemSubID = 955;
        Kapton.setProcessingMaterialTierEU(TierEU.RECIPE_UV);

        SinteredSiliconCarbide = new MaterialBuilder()
            .setName("SinteredSiliconCarbide")
            .setDefaultLocalName("Sintered Silicon Carbide")
            .setChemicalFormula("SiC")
            .setColor(Dyes.dyeGray)
            .setARGB(0xFF3D3D40)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .setMeltingPoint(3003)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        SinteredSiliconCarbide.mMetaItemSubID = 957;
        SinteredSiliconCarbide.setProcessingMaterialTierEU(TierEU.RECIPE_UV);

        HexagonalBoronNitride = new MaterialBuilder()
            .setName("HexagonalBoronNitride")
            .setDefaultLocalName("Hexagonal Boron Nitride")
            .setChemicalFormula("BN")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF0F0EC)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setMeltingPoint(3246)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingot)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        HexagonalBoronNitride.mMetaItemSubID = 958;
        HexagonalBoronNitride.setProcessingMaterialTierEU(TierEU.RECIPE_UHV);

        CarbonFiberComposite = new MaterialBuilder()
            .setName("CarbonFiberComposite")
            .setDefaultLocalName("Carbon Fiber Composite")
            .setColor(Dyes.dyeBlack)
            .setARGB(0xFF1A1A2E)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        CarbonFiberComposite.mMetaItemSubID = 959;
        CarbonFiberComposite.setProcessingMaterialTierEU(TierEU.RECIPE_UV);

        SilicaAerogel = new MaterialBuilder()
            .setName("SilicaAerogel")
            .setDefaultLocalName("Silica Aerogel")
            .setChemicalFormula("SiO₂")
            .setColor(Dyes.dyeLightBlue)
            .setARGB(0xFFD0E8FF)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        SilicaAerogel.mMetaItemSubID = 960;
        SilicaAerogel.setProcessingMaterialTierEU(TierEU.RECIPE_UHV);

        /*
         * =========================
         * FLUID INTERMEDIATES
         * =========================
         */

        TEOS = new MaterialBuilder()
            .setName("TEOS")
            .setDefaultLocalName("Tetraethyl Orthosilicate")
            .setChemicalFormula("Si(OC₂H₅)₄")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFE8F4FF)
            .setMoltenARGB(0xFFD0ECFF)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        TEOS.mMetaItemSubID = 961;

        PAASolution = new MaterialBuilder()
            .setName("PAASolution")
            .setDefaultLocalName("Polyamic Acid Solution")
            .setChemicalFormula("(C₂₂H₁₄N₂O₇)")
            .setColor(Dyes.dyeYellow)
            .setARGB(0xFFFFE082)
            .setMoltenARGB(0xFFFFD54F)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        PAASolution.mMetaItemSubID = 962;

        /*
         * =========================
         * NYLON CHEMISTRY FLUIDS
         * =========================
         */

        AdipicAcid = new MaterialBuilder()
            .setName("AdipicAcid")
            .setDefaultLocalName("Adipic Acid")
            .setChemicalFormula("C₆H₁₀O₄")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFFFF0D0)
            .setMoltenARGB(0xFFFFE8B0)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        AdipicAcid.mMetaItemSubID = 963;

        Hexamethylenediamine = new MaterialBuilder()
            .setName("Hexamethylenediamine")
            .setDefaultLocalName("Hexamethylenediamine")
            .setChemicalFormula("C₆H₁₆N₂")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF0F0FF)
            .setMoltenARGB(0xFFE0E0FF)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        Hexamethylenediamine.mMetaItemSubID = 964;

        Cyclohexanol = new MaterialBuilder()
            .setName("Cyclohexanol")
            .setDefaultLocalName("Cyclohexanol")
            .setChemicalFormula("C₆H₁₂O")
            .setColor(Dyes.dyeBrown)
            .setARGB(0xFF411F00)
            .setMoltenARGB(0xFF5A2D00)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        Cyclohexanol.mMetaItemSubID = 965;

        KetoneAlcholSolution = new MaterialBuilder()
            .setName("KetoneAlcholSolution")
            .setDefaultLocalName("Ketone-Alchol Solution")
            .setChemicalFormula("CH3COCH2OH")
            .setColor(Dyes.dyeBrown)
            .setARGB(0xFF411F00)
            .setMoltenARGB(0xFF5A2D00)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();

        Cyclohexene = new MaterialBuilder()
            .setName("Cyclohexene")
            .setDefaultLocalName("Cyclohexene")
            .setChemicalFormula("(CH₂)₄C₂H₂")
            .setColor(Dyes.dyeBrown)
            .setARGB(0xFF411F00)
            .setMoltenARGB(0xFF5A2D00)
            .setIconSet(TextureSet.SET_FLUID)
            .setUnifiable(false)
            .addCell()
            .addElectrolyzerRecipe()
            .setAutoGeneratedRecycleRecipes(true)
            .addFluid()
            .constructMaterial();
        Cyclohexanol.mMetaItemSubID = 965;
    }
}
