package com.gtnh.processingplus.materials;

import gregtech.api.enums.Dyes;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TextureSet;
import gregtech.api.interfaces.IMaterialHandler;

public class GTNHPPMaterials implements IMaterialHandler {

    public static Materials Nylon66;
    public static Materials PolylacticAcid;
    public static Materials Kapton;
    public static Materials SiliconCarbide;
    public static Materials HexagonalBoronNitride;
    public static Materials CarbonFiberComposite;
    public static Materials SilicaAerogel;

    @Override
    public void onMaterialsInit() {
        Nylon66 = new MaterialBuilder()
            .setName("Nylon66")
            .setDefaultLocalName("Nylon-6,6")
            .setChemicalFormula("(C12H22N2O2)n")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF5EAD0)
            .setMoltenARGB(0xFFD4C8A0)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .addFluid()
            .setMeltingPoint(533)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        Nylon66.mMetaItemSubID = 953;

        PolylacticAcid = new MaterialBuilder()
            .setName("PolylacticAcid")
            .setDefaultLocalName("Polylactic Acid")
            .setChemicalFormula("(C3H4O2)n")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF5F5F0)
            .setMoltenARGB(0xFFD8D8D0)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .addFluid()
            .setMeltingPoint(453)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        PolylacticAcid.mMetaItemSubID = 954;

        // Kapton decomposes above ~630°C — no melt, no ingot, ceramic-style forms only
        Kapton = new MaterialBuilder()
            .setName("Kapton")
            .setDefaultLocalName("Polyimide (Kapton)")
            .setChemicalFormula("(C22H10N2O5)n")
            .setColor(Dyes.dyeYellow)
            .setARGB(0xFFCC8800)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        Kapton.mMetaItemSubID = 955;

        // SiC: sintered ceramic — plate/rod/gear/round only, no ingot
        SiliconCarbide = new MaterialBuilder()
            .setName("SiliconCarbide")
            .setDefaultLocalName("Silicon Carbide")
            .setChemicalFormula("SiC")
            .setColor(Dyes.dyeGray)
            .setARGB(0xFF3D3D40)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .setMeltingPoint(3003)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        SiliconCarbide.mMetaItemSubID = 957;

        // hBN: hot-pressed ceramic — dust + plate only
        HexagonalBoronNitride = new MaterialBuilder()
            .setName("HexagonalBoronNitride")
            .setDefaultLocalName("Hexagonal Boron Nitride")
            .setChemicalFormula("BN")
            .setColor(Dyes.dyeWhite)
            .setARGB(0xFFF0F0EC)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setMeltingPoint(3246)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        HexagonalBoronNitride.mMetaItemSubID = 958;

        // CFC: plate/rod/foil/gear/round/spring, no ingot/bolt/screw/ring
        CarbonFiberComposite = new MaterialBuilder()
            .setName("CarbonFiberComposite")
            .setDefaultLocalName("Carbon Fiber Composite")
            .setColor(Dyes.dyeBlack)
            .setARGB(0xFF1A1A2E)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        CarbonFiberComposite.mMetaItemSubID = 959;

        // Aerogel: dust + plate only (extremely fragile)
        SilicaAerogel = new MaterialBuilder()
            .setName("SilicaAerogel")
            .setDefaultLocalName("Silica Aerogel")
            .setChemicalFormula("SiO2")
            .setColor(Dyes.dyeLightBlue)
            .setARGB(0xFFD0E8FF)
            .setIconSet(TextureSet.SET_DULL)
            .setUnifiable(true)
            .addDustItems()
            .addMetalItems()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedRecycleRecipes(true)
            .removeOrePrefix(OrePrefixes.ingotHot)
            .constructMaterial();
        SilicaAerogel.mMetaItemSubID = 960;
    }
}
